### ISSUE TITLE
Run tests in tearoff namespace, or otherwise prevent pollution of namespaces

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/minitest#1]
Otherwise defs in test blocks pollute the namespace ... I noticed due to a :refer :all .. perhaps this is a non-issue

**Comment by ggeoffrey** [comment]
Rewriting `def` into `let` ?

**Comment by dustingetz** [comment]
I'm not sure if this is even reasonable, because the "REPL" experience would pollute the namespace and we want it to be intuitive
