### ISSUE TITLE
Pattern matching or destructuring in expectations

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/minitest#2]
e.g. `=> [{'>c _} 3]` could match `[{>c #object[hyperfiddle.View 0x222d287f "hyperfiddle.View@222d287f"]} 3]`

**Comment by TristeFigure** [comment]
I have code to destructure destructuring forms. It's well tested and it's ready to bee exported as a separate lib (it's in my general toolbox repo for now).

**Comment by ggeoffrey** [comment]
This one is top priority after release

**Comment by ggeoffrey** [comment]
```clojure
(tests
  {1 _, 2 _} := {1 :foo, 2 :bar})
```
pass, because `1=1`, `2=2`, `:foo` and `:bar` ignored
