### ISSUE TITLE
Sending file contents shouldn't causes dependency namespaces to run tests

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/minitest#5]
Loading a file should run the tests in that file, but not transitive tests. (If I want to check a dependency's tests, I can go load that file explicitly)

**Comment by dustingetz** [comment]
This is won't-fix for shadow-cljs, for now due to shadow-cljs using nonstandard module loading require strategy (not goog.require).

**Comment by ggeoffrey** [comment]
Some context/vocabulary

```
| Thing        | what it means                                               |
|--------------+-------------------------------------------------------------|
| eval mode    | sending a test form to the repl                             |
| require mode | the user requires a namespace containing tests, at the repl |
| load mode    | the runtime requires a namespace containing tests, no repl  |


(ns foo)
(tests
  foo := "bar")


(require 'foo)

lein run

```

**Comment by dustingetz** [comment]
This might be a cursive-specific issue, it only seems to happen on first load, and Cursive has odd behavior:

> "Load file in REPL" will calculate all the namespace dependencies of the file you're loading, and will also load those dependencies in the correct order if any of them are out of date. This is very useful when editing multi-namespace projects as it's often easy to forget when you've updated a file containing a function used by the main code you're working on. It's also very useful when working on code that's require'd by its tests.

https://cursive-ide.com/userguide/repl.html#interaction-with-the-editor

**Comment by dustingetz** [comment]
If we confirm this is cursive-only I will tag with won't-fix
